---
collections:
  - name: ansible.netcommon
    version: 8.6.2
  - name: ansible.utils
    version: 6.1.0
  - name: community.vmware
    version: 4.8.0
  - name: infra.controller_configuration
    version: 3.4.0
  - name: junipernetworks.junos
    version: 9.1.0
