#!/bin/bash
set -euo pipefail

lab_file='/opt/unetlab/labs/Tech Little Brawta Lab.unl'
tenant='43'
session='4'

/opt/unetlab/wrappers/unl_wrapper \
  -a start \
  -T "$tenant" \
  -S "$session" \
  -F "$lab_file"
